# Generated by Django 5.2 on 2025-05-14 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custormer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custormer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custormer',
            new_name='customer',
        ),
    ]
